# Generated by Django 4.0.4 on 2022-05-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('flight_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('departure_loc', models.CharField(max_length=50)),
                ('arrival_loc', models.CharField(max_length=50)),
                ('flight_date', models.DateField()),
                ('dept_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('terminal', models.CharField(max_length=10)),
                ('gate', models.CharField(max_length=10)),
                ('boarding_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('seat', models.CharField(max_length=3)),
                ('e_ticket_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pnr', models.CharField(max_length=10)),
                ('Class', models.CharField(max_length=20)),
                ('flight_no', models.CharField(max_length=30)),
                ('facedetected', models.BooleanField(default=False)),
            ],
        ),
    ]
